feat!: replace pip packages with system packages
The original install function fails on Ubuntu 24.04 LTS+.
  error: externally-managed-environment

Instead of installing `powerline` and `powerline-gitstatus` with `pip`,
install `python3-powerline` and `python3-powerline-gitstatus` with
`apt`.